services:

  postgres:
    image: postgres:15
    restart: always
    environment:
      POSTGRES_DB: ordersdb
      POSTGRES_USER: orders
      POSTGRES_PASSWORD: orderspass
    ports:
      - "5432:5432"
    networks:
      - chat-network

  chat-service:
    build:
      context: ./services/chat_service
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    environment:
      - OTEL_SERVICE_NAME=chat-service
      - OTEL_EXPORTER_OTLP_PROTOCOL=http/protobuf
      - OTEL_EXPORTER_OTLP_ENDPOINT=http://otel-collector:4318
    env_file:
      - ./.env
    networks:
      - chat-network
  # ecommerce-app:
  #   build:
  #     context: ./ecommerce-app
  #     dockerfile: Dockerfile
  #   ports:
  #     - "4200:80"
  #   environment:
  #     - NG_APP_CHAT_ENDPOINT=${CHAT_ENDPOINT}
  #     - NG_APP_OTLP_ENDPOINT=${OTEL_EXPORTER_OTLP_ENDPOINT}
  #   env_file:
  #     - ./.env
  #   depends_on:
  #     - chat-service
  #     - otel-collector
  #   networks:
  #     - chat-network


  otel-collector:
    image: honeycombio/honeycomb-opentelemetry-collector:latest
#    build:
#      context: packages/client
#      dockerfile: Dockerfile
#      args:
#        - SYMBOLS_PATH=/symbols
#      target: collector-local
    volumes:
      - ./otel-collector/otel-collector-config.yaml:/config.yaml
    environment:
      HONEYCOMB_API_KEY: ${HONEYCOMB_API_KEY}
    env_file:
      - ./.env
    networks:
      - chat-network
    ports:
      - "4317:4317" # OTLP gRPC receiver
      - "4318:4318" # OTLP http receiver

networks:
  chat-network:
    driver: bridge
