receivers:
  otlp:
    protocols:
      http:
        endpoint: 0.0.0.0:4318
        cors:
          allowed_origins:
            - http://localhost:4200
            - http://localhost:5173
            - http://ecommerce-app:8081
            - http://localhost:8080
          allowed_headers:
            - "*"
processors:
  batch:

exporters:
  debug:
   # verbosity: detailed

  otlp:
    endpoint: https://api.honeycomb.io:443
    headers:
      "x-honeycomb-team": "${HONEYCOMB_API_KEY}"

service:
  telemetry:
    logs:
  pipelines:
    traces:
      receivers: [otlp]
      #processors: [symbolicator, batch]
      processors: [batch]
      exporters: [debug, otlp]
    logs:
      receivers: [otlp]
      processors: [batch]
      exporters: [debug, otlp]
    metrics:
      receivers: [otlp]
      processors: [batch]
      exporters: [debug, otlp]
