spring:
  application:
    name: ecommerce-service
  datasource:
    url: jdbc:postgresql://postgres:${POSTGRES_PORT}/${POSTGRES_DB}
    username: ${POSTGRES_USER}
    password: ${POSTGRES_PASSWORD}
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
  # flyway:
  #   enabled: true
  #   locations: filesystem:../../db/migrations
  #   baseline-on-migrate: true
  #   validate-on-migrate: true

server:
  port: 8081

logging:
  level:
    org.springframework.web: debug

otel:
  propagators: tracecontext
  resource:
    attributes:
      service:
        name: ecommerce-service
  instrumentation:
    # logback-appender:
    #   enabled: false
    # slf4j-simple:
    #   enabled: false
    common:
      experimental:
        controller:
          controller-telemetry: enabled

# Could also add this, but Spring Boot grabs from environment already
#  exporter:
#    otlp:
#      traces:
#        headers:
#          x-honeycomb-team: ${HONEYCOMB_API_KEY}

#       namespace: shop
#       deployment:
#         environment: dev
